Matrices! Added mat3 and mat4
PikoStudios/Muzzle pull request #36
Opened 2023-01-22 20:55 UTC by Vaimer9

2023-01-22 20:55 UTC, Vaimer9 commented
#34

2023-01-22 20:57 UTC, Vaimer9 commented
It seems as if I removed the newlines at the end of the files, due to unix encoding. Was worried that would happen. Let me know if thats a problem.

2023-01-22 22:39 UTC, OkiStuff requested changes
Good PR, just one thing:

 - The mat3 and mat4 types do not specify size, it is not guaranteed that these are an array, simply a pointer to a float, or an array that does not match the needed size. `typedef int array_type_example[5]; array_type_example my_array = {1,2,3,4,5}`.
 - It may also be a good idea to check if the array is NULL, but I can implement that as I want to rework assertions in Muzzle.

2023-01-23 10:17 UTC, Vaimer9 commented
> Good PR, just one thing:
> 
> * The mat3 and mat4 types do not specify size, it is not guaranteed that these are an array, simply a pointer to a float, or an array that does not match the needed size. `typedef int array_type_example[5]; array_type_example my_array = {1,2,3,4,5}`.
> * It may also be a good idea to check if the array is NULL, but I can implement that as I want to rework assertions in Muzzle.

What exactly should be done if the array is NULL? Should I check the entire array's size?

2023-01-23 10:51 UTC, OkiStuff commented
> > Good PR, just one thing:
> 
> > 
> 
> > * The mat3 and mat4 types do not specify size, it is not guaranteed that these are an array, simply a pointer to a float, or an array that does not match the needed size. `typedef int array_type_example[5]; array_type_example my_array = {1,2,3,4,5}`.
> 
> > * It may also be a good idea to check if the array is NULL, but I can implement that as I want to rework assertions in Muzzle.
> 
> 
> 
> What exactly should be done if the array is NULL? Should I check the entire array's size for NULL?

No, just the pointer. Also use `log_status()` for Error Logging. Again I can do that part? I just need the sized types

2023-01-23 18:08 UTC, merged

2023-01-23 18:09 UTC, OkiStuff commented
NOTE: Commit was squashed into one commit.